name = "MakieRepel"
uuid = "79acca00-33c7-41d8-a12e-17f03a17ec78"
authors = ["Anshul Singhvi <anshulsinghvi@gmail.com> and contributors"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
julia = "1.5"
Makie = "0.17, 0.18, 0.19"
StructArrays = "0.6"
BenchmarkTools = "1"
TimerOutputs = "0.5"


[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "RDatasets", "CairoMakie", "BenchmarkTools", "TimerOutputs"]
